### ISSUE TITLE
Update Speeduino codebase

### ISSUE THREAD

**Issue by masrodjie** [DeeEmm/sparkduino#3]
Is there any plan to update Speeduino codebase to latest? Thank you

**Comment by DeeEmm** [comment]
Hi @masrodjie I have not maintained this project as it is simply possible to use the Speeduino firmware unmodified for spark only applications.

The main difference between this project and the Speediuno code was that the INI file was modified to hide the non spark related dashboard items in Tuner Studio. The main code remained the same.

I developed this as I used the Speeduino code in an ignition system that I sold. The idea was to hide the fuel related gauges in the Tuner Studio dashboard to help simplify things for the end user. 

You can of course achieve the same by designing a custom Tuner Studio dashboard

If you are interested in how this project differs you can do a compare with the equivalent Speeduino firmware version.

HTH.

/DM

**Comment by masrodjie** [comment]
I see. Thank you so much. Do you have example msq tune? Is it still need IAT and CLT sensor or can we skip it?

**Comment by DeeEmm** [comment]
I used both the IAT and CLT sensors. Many of the applications that I sold were forced inductions, so the IAT offers some protection with the IAT retard function. Similarly with CLT you can also modify timing as part of the warm up settings.

But, it will work fine without them. You just need to zero out the relevant settings so that they done have an impact. I would also advise to tie both inputs to a know resistor value so they they are held at a stable value.

Sorry I don't have an MSQ file.
